export const CADASTRO_START = 'CADASTRO_START';
export const CADASTRO_SUCCESS = 'CADASTRO_SUCCESS';
export const CADASTRO_FAIL = 'CADASTRO_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const RESERVAR_START = 'RESERVAR_START';
export const RESERVAR_SUCCESS = 'RESERVAR_SUCCESS';
export const RESERVAR_FAIL = 'RESERVAR_FAIL';

export const MINHAS_RESERVAS_START = 'MINHAS_RESERVAS_START';
export const MINHAS_RESERVAS_SUCCESS = 'MINHAS_RESERVAS_SUCCESS';
export const MINHAS_RESERVAS_FAIL = 'MINHAS_RESERVAS_FAIL';

export const DATAS_RESERVADAS_START = 'DATAS_RESERVADAS_START';
export const DATAS_RESERVADAS_SUCCESS = 'DATAS_RESERVADAS_SUCCESS';
export const DATAS_RESERVADAS_FAIL = 'DATAS_RESERVADAS_FAIL';