export const CADASTRO_START = 'CADASTRO_START';
export const CADASTRO_SUCCESS = 'CADASTRO_SUCCESS';
export const CADASTRO_FAIL = 'CADASTRO_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';