export const CADASTRO_START = 'CADASTRO_START';
export const CADASTRO_SUCCESS = 'CADASTRO_SUCCESS';
export const CADASTRO_FAIL = 'CADASTRO_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const RESERVAR_START = 'RESERVAR_START';
export const RESERVAR_SUCCESS = 'RESERVAR_SUCCESS';
export const RESERVAR_FAIL = 'RESERVAR_FAIL';